# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfd3b371231e2e5131629ee9e0932519b1aacd910a0ad982abaae606dfadc97d19a5d5def271286012342352a0dca5df115108516a86622f14d5262929553ace

test:
  secret_key_base: 12ce21bb360a7533e008be5241dde134052d80b942eee85304996c99d3ad329f6c0cabd9036f9aa6ae98e1436cd24fab9701a160e04c8393c028d0075cb8c815

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
